import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

// 业务类型列表
final List<Map<String, dynamic>> businessTypes = [
  {
    'name': '代码分析',
    'icon': Icons.code,
    'description': '代码审查、调试、重构和优化建议',
    'color': Colors.blue,
  },
  {
    'name': '法律查询',
    'icon': Icons.gavel,
    'description': '法律条文查询、合同审查、法律咨询',
    'color': Colors.purple,
  },
  {
    'name': '合规管理',
    'icon': Icons.security,
    'description': '企业合规检查、风险评估、政策解读',
    'color': Colors.orange,
  },
  {
    'name': '通用对话',
    'icon': Icons.chat,
    'description': '日常对话、问答、知识查询',
    'color': Colors.green,
  },
  {
    'name': '文档处理',
    'icon': Icons.description,
    'description': '文档总结、翻译、格式转换',
    'color': Colors.indigo,
  },
  {
    'name': '数据分析',
    'icon': Icons.analytics,
    'description': '数据处理、图表生成、统计分析',
    'color': Colors.teal,
  },
];

// 在线模型提供商列表
final List<Map<String, dynamic>> onlineProviders = [
  {
    'name': 'DeepSeek',
    'id': 'deepseek',
    'protocol': 'openai',
    'icon': CupertinoIcons.cube_box,
    'description': '高性能AI助手，支持多种任务',
    'color': const Color(0xFF3B82F6),
    'defaultUrl': 'https://api.deepseek.com',
    'models': [
      {'id': 'deepseek-v4-flash', 'name': 'DeepSeek-V4-Flash', 'specs': '快速响应 • 高性价比 • 通用对话', },
      {'id': 'deepseek-v4-pro', 'name': 'DeepSeek-V4-Pro', 'specs': '深度推理 • 复杂问题 • 思维链',},
    ],
  },
  {
    'name': 'ChatGPT',
    'id': 'openai',
    'protocol': 'openai',
    'icon': CupertinoIcons.command,
    'description': 'OpenAI GPT系列模型',
    'color': const Color(0xFF10B981),
    'defaultUrl': 'https://api.openai.com/v1',
    'models': [
      {'id': 'gpt-4o', 'name': 'GPT-4o', 'specs': '多模态 • 高级推理 • 最新旗舰'},
      {'id': 'gpt-4-turbo', 'name': 'GPT-4 Turbo', 'specs': '更快响应 • 128K上下文'},
      {'id': 'gpt-3.5-turbo', 'name': 'GPT-3.5 Turbo', 'specs': '快速响应 • 高性价比'},
    ],
  },
  {
    'name': 'Gemini',
    'id': 'google',
    'protocol': 'gemini',
    'icon': CupertinoIcons.person,
    'description': 'Google Gemini系列模型',
    'color': const Color(0xFFEF4444),
    'defaultUrl': 'https://generativelanguage.googleapis.com/v1',
    'models': [
      {'id': 'gemini-pro', 'name': 'Gemini Pro', 'specs': '多模态 • 长上下文 • Google'},
      {'id': 'gemini-pro-vision', 'name': 'Gemini Pro Vision', 'specs': '视觉理解 • 图像分析 • 多模态'},
      {'id': 'gemini-2.0-flash', 'name': 'Gemini 2.0 Flash', 'specs': '极速响应 • 多模态 • 轻量'},
    ],
  },
  {
    'name': '阿里云百炼',
    'id': 'qwen',
    'protocol': 'openai',
    'icon': CupertinoIcons.chat_bubble_2,
    'description': '阿里云百炼平台模型服务',
    'color': const Color(0xFF8B5CF6),
    'defaultUrl': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    'models': [
      // ===== 推荐模型 =====
      {'id': 'qwen3.7-max', 'name': 'Qwen3.7-Max', 'specs': '1M上下文 • 最强推理 • 思考模式 • 工具调用', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen3.7-plus', 'name': 'Qwen3.7-Plus', 'specs': '1M上下文 • 能力成本均衡 • 思考模式 • 工具调用', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen3.6-flash', 'name': 'Qwen3.6-Flash', 'specs': '1M上下文 • 轻量低成本 • 思考模式 • 工具调用', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'deepseek-v4-pro', 'name': 'DeepSeek-V4-Pro', 'specs': '1M上下文 • 深度推理 • Function Calling', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-v4-flash', 'name': 'DeepSeek-V4-Flash', 'specs': '1M上下文 • 快速推理 • Function Calling', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'glm-5.1', 'name': 'GLM-5.1', 'specs': '198k上下文 • 智能体优化 • 思考模式 • 结构化输出', 'context': '198k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'kimi-k2.6', 'name': 'Kimi-K2.6', 'specs': '256k上下文 • 思考模式 • Function Calling', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'MiniMax-M2.5', 'name': 'MiniMax-M2.5', 'specs': '192k上下文 • 智能体优化 • Function Calling', 'context': '192k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'mimo-v2.5-pro', 'name': 'Mimo-V2.5-Pro', 'specs': '1M上下文 • 思考模式 • 结构化输出', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      // ===== Qwen3.7 系列 =====
      {'id': 'qwen3.7-max-2026-05-20', 'name': 'Qwen3.7-Max (05-20)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.7-max-preview', 'name': 'Qwen3.7-Max Preview', 'specs': '1M上下文 • 预览版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.7-plus-2026-05-26', 'name': 'Qwen3.7-Plus (05-26)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      // ===== Qwen3.6 系列 =====
      {'id': 'qwen3.6-max-preview', 'name': 'Qwen3.6-Max Preview', 'specs': '256k上下文 • 预览版', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.6-plus', 'name': 'Qwen3.6-Plus', 'specs': '1M上下文 • 思考模式 • 工具调用', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen3.6-plus-2026-04-02', 'name': 'Qwen3.6-Plus (04-02)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.6-flash-2026-04-16', 'name': 'Qwen3.6-Flash (04-16)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      // ===== Qwen3.5 系列 =====
      {'id': 'qwen3.5-plus', 'name': 'Qwen3.5-Plus', 'specs': '1M上下文 • 思考模式 • 工具调用', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen3.5-plus-2026-02-15', 'name': 'Qwen3.5-Plus (02-15)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.5-flash', 'name': 'Qwen3.5-Flash', 'specs': '1M上下文 • 思考模式 • 工具调用', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen3.5-flash-2026-02-23', 'name': 'Qwen3.5-Flash (02-23)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.5-397b-a17b', 'name': 'Qwen3.5-397B-A17B', 'specs': '256k上下文 • MoE架构 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.5-122b-a10b', 'name': 'Qwen3.5-122B-A10B', 'specs': '256k上下文 • MoE架构 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.5-27b', 'name': 'Qwen3.5-27B', 'specs': '256k上下文 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3.5-35b-a3b', 'name': 'Qwen3.5-35B-A3B', 'specs': '256k上下文 • MoE轻量 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      // ===== 第三方模型 =====
      {'id': 'glm-5', 'name': 'GLM-5', 'specs': '198k上下文 • 思考模式 • Function Calling', 'context': '198k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'glm-4.7', 'name': 'GLM-4.7', 'specs': '198k上下文 • 思考模式 • Function Calling', 'context': '198k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'glm-4.5', 'name': 'GLM-4.5', 'specs': '198k上下文 • 思考模式 • Function Calling', 'context': '198k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'glm-4.5-air', 'name': 'GLM-4.5-Air', 'specs': '198k上下文 • 轻量版', 'context': '198k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'MiniMax-M2.1', 'name': 'MiniMax-M2.1', 'specs': '200k上下文 • 思考模式 • Function Calling', 'context': '200k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'kimi-k2.5', 'name': 'Kimi-K2.5', 'specs': '256k上下文 • 思考模式 • Function Calling', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'kimi-k2-thinking', 'name': 'Kimi-K2-Thinking', 'specs': '256k上下文 • 深度思考 • 结构化输出', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'Moonshot-Kimi-K2-Instruct', 'name': 'Kimi-K2-Instruct', 'specs': '256k上下文 • 开源 • Function Calling', 'context': '256k', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-v3.2', 'name': 'DeepSeek-V3.2', 'specs': '128k上下文 • 思考模式 • Function Calling', 'context': '128k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': true},
      {'id': 'deepseek-v3.2-exp', 'name': 'DeepSeek-V3.2-Exp', 'specs': '128k上下文 • 实验版', 'context': '128k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-v3.1', 'name': 'DeepSeek-V3.1', 'specs': '128k上下文 • 思考模式 • Function Calling', 'context': '128k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': true},
      {'id': 'deepseek-v3', 'name': 'DeepSeek-V3', 'specs': '128k上下文 • Function Calling', 'context': '128k', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': true},
      {'id': 'deepseek-r1', 'name': 'DeepSeek-R1', 'specs': '128k上下文 • 深度推理 • Function Calling', 'context': '128k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': true},
      {'id': 'deepseek-r1-0528', 'name': 'DeepSeek-R1-0528', 'specs': '128k上下文 • 深度推理 • 快照版', 'context': '128k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-r1-distill-llama-70b', 'name': 'DeepSeek-R1-Distill-70B', 'specs': '128k上下文 • 蒸馏版 • 思考模式', 'context': '128k', 'thinking': true, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-r1-distill-qwen-32b', 'name': 'DeepSeek-R1-Distill-32B', 'specs': '128k上下文 • 蒸馏版', 'context': '128k', 'thinking': true, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-r1-distill-qwen-14b', 'name': 'DeepSeek-R1-Distill-14B', 'specs': '128k上下文 • 蒸馏版', 'context': '128k', 'thinking': true, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-r1-distill-qwen-7b', 'name': 'DeepSeek-R1-Distill-7B', 'specs': '128k上下文 • 蒸馏版', 'context': '128k', 'thinking': true, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-r1-distill-qwen-1.5b', 'name': 'DeepSeek-R1-Distill-1.5B', 'specs': '128k上下文 • 蒸馏版 • 轻量', 'context': '128k', 'thinking': true, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'deepseek-r1-distill-llama-8b', 'name': 'DeepSeek-R1-Distill-8B', 'specs': '128k上下文 • 蒸馏版 • 轻量', 'context': '128k', 'thinking': true, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      // ===== Qwen3 系列 =====
      {'id': 'qwen3-max', 'name': 'Qwen3-Max', 'specs': '256k上下文 • 思考模式 • 工具调用 • 结构化输出', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen3-max-2026-01-23', 'name': 'Qwen3-Max (01-23)', 'specs': '256k上下文 • 快照版', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-max-preview', 'name': 'Qwen3-Max Preview', 'specs': '256k上下文 • 预览版', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-235b-a22b', 'name': 'Qwen3-235B-A22B', 'specs': '256k上下文 • MoE架构 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-32b', 'name': 'Qwen3-32B', 'specs': '256k上下文 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-30b-a3b', 'name': 'Qwen3-30B-A3B', 'specs': '256k上下文 • MoE轻量 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-14b', 'name': 'Qwen3-14B', 'specs': '256k上下文 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-8b', 'name': 'Qwen3-8B', 'specs': '256k上下文 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-4b', 'name': 'Qwen3-4B', 'specs': '256k上下文 • 开源', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-1.7b', 'name': 'Qwen3-1.7B', 'specs': '256k上下文 • 开源 • 轻量', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-0.6b', 'name': 'Qwen3-0.6B', 'specs': '256k上下文 • 开源 • 极轻量', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      // ===== Qwen3-Coder 系列 =====
      {'id': 'qwen3-coder-plus', 'name': 'Qwen3-Coder-Plus', 'specs': '1M上下文 • 代码专用', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-coder-plus-2025-09-23', 'name': 'Qwen3-Coder-Plus (09-23)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-coder-plus-2025-07-22', 'name': 'Qwen3-Coder-Plus (07-22)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-coder-flash', 'name': 'Qwen3-Coder-Flash', 'specs': '1M上下文 • 代码专用 • 轻量快速', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-coder-flash-2025-07-28', 'name': 'Qwen3-Coder-Flash (07-28)', 'specs': '1M上下文 • 快照版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-coder-next', 'name': 'Qwen3-Coder-Next', 'specs': '256k上下文 • 代码专用', 'context': '256k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-coder-480b-a35b-instruct', 'name': 'Qwen3-Coder-480B-Instruct', 'specs': '256k上下文 • 开源 • 代码专用', 'context': '256k', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen3-coder-30b-a3b-instruct', 'name': 'Qwen3-Coder-30B-Instruct', 'specs': '256k上下文 • 开源 • 代码专用', 'context': '256k', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      // ===== Qwen2.5 开源系列 =====
      {'id': 'qwen2.5-vl-72b-instruct', 'name': 'Qwen2.5-VL-72B', 'specs': '1M上下文 • 视觉理解 • 多模态', 'context': '1M', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'qwen2.5-vl-32b-instruct', 'name': 'Qwen2.5-VL-32B', 'specs': '1M上下文 • 视觉理解 • 多模态', 'context': '1M', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'qwen2.5-vl-7b-instruct', 'name': 'Qwen2.5-VL-7B', 'specs': '1M上下文 • 视觉理解 • 轻量', 'context': '1M', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'qwen2.5-vl-3b-instruct', 'name': 'Qwen2.5-VL-3B', 'specs': '1M上下文 • 视觉理解 • 极轻量', 'context': '1M', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'qwen2.5-72b-instruct', 'name': 'Qwen2.5-72B-Instruct', 'specs': '1M上下文 • 开源 • Function Calling', 'context': '1M', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen2.5-32b-instruct', 'name': 'Qwen2.5-32B-Instruct', 'specs': '1M上下文 • 开源 • Function Calling', 'context': '1M', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen2.5-14b-instruct', 'name': 'Qwen2.5-14B-Instruct', 'specs': '1M上下文 • 开源 • Function Calling', 'context': '1M', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen2.5-7b-instruct', 'name': 'Qwen2.5-7B-Instruct', 'specs': '1M上下文 • 开源 • 轻量', 'context': '1M', 'thinking': false, 'fc': true, 'tools': false, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'qwen2.5-omni-7b', 'name': 'Qwen2.5-Omni-7B', 'specs': '1M上下文 • 多模态 • 语音图文', 'context': '1M', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      // ===== Qwen Long =====
      {'id': 'qwen-long', 'name': 'Qwen-Long', 'specs': '10M上下文 • 超长文档 • 结构化输出', 'context': '10M', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen-long-latest', 'name': 'Qwen-Long-Latest', 'specs': '10M上下文 • 超长文档 • 最新版', 'context': '10M', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': true, 'batchCalling': true},
      // ===== 旧版模型 =====
      {'id': 'qwen-plus', 'name': 'Qwen-Plus', 'specs': '1M上下文 • 思考模式 • 工具调用 • 旧版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen-max', 'name': 'Qwen-Max', 'specs': '128k上下文 • 思考模式 • 工具调用 • 旧版', 'context': '128k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwen-turbo', 'name': 'Qwen-Turbo', 'specs': '1M上下文 • 思考模式 • 工具调用 • 旧版', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': true},
      {'id': 'qwq-plus', 'name': 'QwQ-Plus', 'specs': '128k上下文 • 思考模式 • 深度推理', 'context': '128k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': true},
      {'id': 'qvq-max', 'name': 'QvQ-Max', 'specs': '128k上下文 • 视觉推理 • 思考模式', 'context': '128k', 'thinking': true, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'qwen-mt-plus', 'name': 'Qwen-MT-Plus', 'specs': '16k上下文 • 翻译专用', 'context': '16k', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'qwen-mt-turbo', 'name': 'Qwen-MT-Turbo', 'specs': '16k上下文 • 翻译专用 • 快速', 'context': '16k', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
    ],
  },
  {
    'name': '腾讯云TokenHub',
    'id': 'tencent',
    'protocol': 'openai',
    'icon': CupertinoIcons.cloud,
    'description': '腾讯云TokenHub大模型服务',
    'color': const Color(0xFF00A4FF),
    'defaultUrl': 'https://api.hunyuan.cloud.tencent.com/v1',
    'models': [
      // ===== 推荐模型 =====
      {'id': 'hy3-preview', 'name': 'Hy3 Preview', 'specs': '256k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'deepseek-v4-flash', 'name': 'DeepSeek-V4-Flash', 'specs': '1M上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'deepseek-v4-pro', 'name': 'DeepSeek-V4-Pro', 'specs': '1M上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      // ===== 混元系列 =====
      {'id': 'hunyuan-role-latest', 'name': 'Hunyuan Role', 'specs': '32k上下文 • 角色扮演 • 对话创作', 'context': '32k', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'hy-mt2-pro', 'name': 'Hy-MT2-Pro', 'specs': '8k上下文 • 翻译旗舰 • 专业领域', 'context': '8k', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'hy-mt2-plus', 'name': 'Hy-MT2-Plus', 'specs': '8k上下文 • 翻译模型 • 指令遵循', 'context': '8k', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'hy-mt2-lite', 'name': 'Hy-MT2-Lite', 'specs': '8k上下文 • 翻译轻量 • 快速响应', 'context': '8k', 'thinking': false, 'fc': false, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      // ===== DeepSeek 系列 =====
      {'id': 'deepseek-v3.2', 'name': 'DeepSeek-V3.2', 'specs': '128k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '128k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      // ===== GLM 系列 =====
      {'id': 'glm-5.2', 'name': 'GLM-5.2', 'specs': '1M上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '1M', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'glm-5.1', 'name': 'GLM-5.1', 'specs': '200k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '200k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'glm-5v-turbo', 'name': 'GLM-5V-Turbo', 'specs': '200k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '200k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'glm-5-turbo', 'name': 'GLM-5-Turbo', 'specs': '200k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '200k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'glm-5', 'name': 'GLM-5', 'specs': '200k上下文 • 深度思考 • Function Calling', 'context': '200k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      // ===== Kimi 系列 =====
      {'id': 'kimi-k2.7-code', 'name': 'Kimi-K2.7-Code', 'specs': '256k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'kimi-k2.6', 'name': 'Kimi-K2.6', 'specs': '256k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      {'id': 'kimi-k2.5', 'name': 'Kimi-K2.5', 'specs': '256k上下文 • 深度思考 • 结构化输出 • Function Calling', 'context': '256k', 'thinking': true, 'fc': true, 'tools': true, 'structuredOutput': true, 'batchCalling': false},
      // ===== MiniMax 系列 =====
      {'id': 'minimax-m3', 'name': 'MiniMax-M3', 'specs': '1M上下文 • 深度思考 • Function Calling', 'context': '1M', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'minimax-m2.7', 'name': 'MiniMax-M2.7', 'specs': '200k上下文 • 深度思考 • Function Calling', 'context': '200k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'minimax-m2.5', 'name': 'MiniMax-M2.5', 'specs': '200k上下文 • 深度思考 • Function Calling', 'context': '200k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      // ===== Qwen 系列 =====
      {'id': 'qwen3.5-flash', 'name': 'Qwen3.5-Flash', 'specs': '991k上下文 • 深度思考 • Function Calling', 'context': '991k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
      {'id': 'qwen3.5-plus', 'name': 'Qwen3.5-Plus', 'specs': '991k上下文 • 深度思考 • Function Calling', 'context': '991k', 'thinking': true, 'fc': true, 'tools': false, 'structuredOutput': false, 'batchCalling': false},
    ],
  },
  {
    'name': 'Mimo',
    'id': 'xiaomi_mimo',
    'protocol': 'openai',
    'icon': CupertinoIcons.device_phone_portrait,
    'description': '小米Mimo大模型服务',
    'color': const Color(0xFFFF6900),
    'defaultUrl': 'https://api.xiaomimimo.com/v1',
    'models': [
      {'id': 'mimo-v2.5-pro', 'name': 'Mimo-V2.5-Pro', 'specs': '1M上下文 • 思考模式 • 结构化输出'},
      {'id': 'mimo-v2.5-lite', 'name': 'Mimo-V2.5-Lite', 'specs': '轻量快速 • 高性价比 • 日常对话'},
    ],
  },
];
