// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/rag/rag_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2427291254187522065),
      name: 'RagChunk',
      lastPropertyId: const obx_int.IdUid(14, 8915503282069050847),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7315479431914948222),
            name: 'obxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2322983327837858376),
            name: 'id',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6806492403935758534),
            name: 'documentId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 4151929041608218679)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5880255232733353955),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 184503596856241988),
            name: 'startPosition',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9207914127268119247),
            name: 'endPosition',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2425818164704995268),
            name: 'chunkIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3721636695803376665),
            name: 'sourceFilePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4618719534939614861),
            name: 'relativePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 3565766560646042824),
            name: 'folderName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1509275965614863330),
            name: 'createdTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6123722966705702991),
            name: 'embeddings',
            type: 29,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 8917263794182828480),
            name: 'comment',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 8915503282069050847),
            name: 'modelId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 2318127421183411635))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 2427291254187522065),
      lastIndexId: const obx_int.IdUid(2, 4151929041608218679),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    RagChunk: obx_int.EntityDefinition<RagChunk>(
        model: _entities[0],
        toOneRelations: (RagChunk object) => [],
        toManyRelations: (RagChunk object) => {},
        getId: (RagChunk object) => object.obxId,
        setId: (RagChunk object, int id) {
          object.obxId = id;
        },
        objectToFB: (RagChunk object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          final documentIdOffset = fbb.writeString(object.documentId);
          final contentOffset = fbb.writeString(object.content);
          final sourceFilePathOffset = fbb.writeString(object.sourceFilePath);
          final relativePathOffset = object.relativePath == null
              ? null
              : fbb.writeString(object.relativePath!);
          final folderNameOffset = object.folderName == null
              ? null
              : fbb.writeString(object.folderName!);
          final embeddingsOffset = object.embeddings == null
              ? null
              : fbb.writeListFloat64(object.embeddings!);
          final commentOffset =
              object.comment == null ? null : fbb.writeString(object.comment!);
          final modelIdOffset = fbb.writeString(object.modelId);
          fbb.startTable(15);
          fbb.addInt64(0, object.obxId);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, documentIdOffset);
          fbb.addOffset(3, contentOffset);
          fbb.addInt64(4, object.startPosition);
          fbb.addInt64(5, object.endPosition);
          fbb.addInt64(6, object.chunkIndex);
          fbb.addOffset(7, sourceFilePathOffset);
          fbb.addOffset(8, relativePathOffset);
          fbb.addOffset(9, folderNameOffset);
          fbb.addInt64(10, object.createdTime.millisecondsSinceEpoch);
          fbb.addOffset(11, embeddingsOffset);
          fbb.addOffset(12, commentOffset);
          fbb.addOffset(13, modelIdOffset);
          fbb.finish(fbb.endTable());
          return object.obxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final obxIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final modelIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 30, '');
          final documentIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final startPositionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final endPositionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final chunkIndexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final sourceFilePathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, '');
          final relativePathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final folderNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final createdTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0));
          final embeddingsParam =
              const fb.ListReader<double>(fb.Float64Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final commentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 28);
          final object = RagChunk(
              obxId: obxIdParam,
              id: idParam,
              modelId: modelIdParam,
              documentId: documentIdParam,
              content: contentParam,
              startPosition: startPositionParam,
              endPosition: endPositionParam,
              chunkIndex: chunkIndexParam,
              sourceFilePath: sourceFilePathParam,
              relativePath: relativePathParam,
              folderName: folderNameParam,
              createdTime: createdTimeParam,
              embeddings: embeddingsParam,
              comment: commentParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RagChunk] entity fields to define ObjectBox queries.
class RagChunk_ {
  /// see [RagChunk.obxId]
  static final obxId =
      obx.QueryIntegerProperty<RagChunk>(_entities[0].properties[0]);

  /// see [RagChunk.id]
  static final id =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[1]);

  /// see [RagChunk.documentId]
  static final documentId =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[2]);

  /// see [RagChunk.content]
  static final content =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[3]);

  /// see [RagChunk.startPosition]
  static final startPosition =
      obx.QueryIntegerProperty<RagChunk>(_entities[0].properties[4]);

  /// see [RagChunk.endPosition]
  static final endPosition =
      obx.QueryIntegerProperty<RagChunk>(_entities[0].properties[5]);

  /// see [RagChunk.chunkIndex]
  static final chunkIndex =
      obx.QueryIntegerProperty<RagChunk>(_entities[0].properties[6]);

  /// see [RagChunk.sourceFilePath]
  static final sourceFilePath =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[7]);

  /// see [RagChunk.relativePath]
  static final relativePath =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[8]);

  /// see [RagChunk.folderName]
  static final folderName =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[9]);

  /// see [RagChunk.createdTime]
  static final createdTime =
      obx.QueryDateProperty<RagChunk>(_entities[0].properties[10]);

  /// see [RagChunk.embeddings]
  static final embeddings =
      obx.QueryDoubleVectorProperty<RagChunk>(_entities[0].properties[11]);

  /// see [RagChunk.comment]
  static final comment =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[12]);

  /// see [RagChunk.modelId]
  static final modelId =
      obx.QueryStringProperty<RagChunk>(_entities[0].properties[13]);
}
